# This file was generated by GoReleaser. DO NOT EDIT.
cask "edgeemu" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "654f4912de85a30b9e23d1770b68b3bc99ced97e8e981207f218cfcd5e22d625"
      url "https://github.com/adzpm/edgeemu-cli/releases/download/v#{version}/edgeemu_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "659ee23ff6b095cabe600dc78fac70e3f8a6df9eb30d3b8e15c321a4358183ab"
      url "https://github.com/adzpm/edgeemu-cli/releases/download/v#{version}/edgeemu_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d178033324c37547f6aaa2cee6cdd4d1c85fe5e73fe762fed409a63cb1c6aedb"
      url "https://github.com/adzpm/edgeemu-cli/releases/download/v#{version}/edgeemu_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "1967daaf38fde70ed9fc787942483edae812b3aff55fee75f97c8fd1c7a2b834"
      url "https://github.com/adzpm/edgeemu-cli/releases/download/v#{version}/edgeemu_#{version}_linux_amd64.tar.gz"
    end
  end

  name "edgeemu"
  desc "CLI for searching ROMs on edgeemu.net"
  homepage "https://github.com/adzpm/edgeemu-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "edgeemu"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/edgeemu"]
    end
  end

  # No zap stanza required
end
