# This file was generated by GoReleaser. DO NOT EDIT.
cask "edgeemu" do
  version "0.2.1"

  on_macos do
    on_arm do
      sha256 "6df983568477bc098ebafe2fd2c1e15daa1604194ba1098a61f91c607a55927f"
      url "https://github.com/adzpm/edgeemu-cli/releases/download/v#{version}/edgeemu_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "9dbd7732d12fe602db49a6a56da19c9411ad1df93ad7440f84c8a6cd38f37a21"
      url "https://github.com/adzpm/edgeemu-cli/releases/download/v#{version}/edgeemu_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "bfbf96d6430438d9e2fe527eacef897192c80e81f4dcc444ccc74341508c70d2"
      url "https://github.com/adzpm/edgeemu-cli/releases/download/v#{version}/edgeemu_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "ac489868bb7e7cdaca25773a4c1e62420302b2b29ab2e69b0ee154cdf64d3682"
      url "https://github.com/adzpm/edgeemu-cli/releases/download/v#{version}/edgeemu_#{version}_linux_amd64.tar.gz"
    end
  end

  name "edgeemu"
  desc "CLI for searching ROMs on edgeemu.net"
  homepage "https://github.com/adzpm/edgeemu-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "edgeemu"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/edgeemu"]
    end
  end

  # No zap stanza required
end
