# This file was generated by GoReleaser. DO NOT EDIT.
cask "edgeemu" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "71218eac4d2f9fcd63964890fad432a79335c9d316627e5a97f6ce1f76bdb238"
      url "https://github.com/adzpm/edgeemu-cli/releases/download/v#{version}/edgeemu_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "e500b2fcd12114578c43ac7d617135d59ed59894cccf06550d2ed6b30e25035e"
      url "https://github.com/adzpm/edgeemu-cli/releases/download/v#{version}/edgeemu_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "00faade36af79666e3b3a90e3bed982d5fe3b87549d49ac5a8a04e68e9b35dc3"
      url "https://github.com/adzpm/edgeemu-cli/releases/download/v#{version}/edgeemu_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "c832418ef3bb818ec2c87cf11efb59cbd336c0fe1b1e7198d3f2e98b46be46ae"
      url "https://github.com/adzpm/edgeemu-cli/releases/download/v#{version}/edgeemu_#{version}_linux_amd64.tar.gz"
    end
  end

  name "edgeemu"
  desc "CLI for searching ROMs on edgeemu.net"
  homepage "https://github.com/adzpm/edgeemu-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "edgeemu"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/edgeemu"]
    end
  end

  # No zap stanza required
end
